version: '3'

services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=kelompok07
      - MYSQL_USER=kelompok07
      - MYSQL_PASSWORD=kelompok07
      - MYSQL_DATABASE=kelompok07
    volumes:
      - squash-tm-db:/var/lib/mysql/data
  main:
    image: apache/openmeetings:7.1.0
    restart: always
    ports:
      - 1443:5443
      - 1888:8888
    environment:
      - OM_DB_HOST=db
volumes:
  squash-tm-db:
